
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

instagram: https://www.instagram.com/dondontam/
github: https://github.com/ChocolateTan
email: 390032295@qq.com

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /poem/css/ss.css
- /poem/assets/css/main.css

stylesheets_no:
- /poem/assets/css/noscript.css

# scripts loaded in the end of the body
scripts:
- /poem/js/ss.js
- /poem/assets/js/jquery.min.js
- /poem/assets/js/browser.min.js
- /poem/assets/js/breakpoints.min.js
- /poem/assets/js/main.js
# - /js/main.js
# - /js/stopExecutionOnTimeout.js
